server:
  grpc_port: 50052

database:
  dsn: "postgres://myuser:mypassword@localhost:5432/mydatabase?sslmode=disable"

kafka:
  group: "alert-triggered-consumer"
  brokers:
    - "localhost:9092"
  topics: 
    - "alerts"
    - "alert_triggered"
